import { AlignLeft, AlignCenter, AlignRight } from 'lucide-react';
import { type Caption, type WordStyle, type CaptionRules } from '@/lib/editor';
import type { EmphasisOptions } from '@/lib/caption-tools';

export function Field({ label, value, min, max, step = 1, onChange }: { label: string; value: number; min: number; max: number; step?: number; onChange: (n: number) => void }) {
  return <label className="inline-field"><span>{label}</span><input aria-label={label} type="number" value={Math.round(value * 100) / 100} min={min} max={max} step={step} onChange={e => { if (e.target.value && Number.isFinite(+e.target.value)) onChange(Math.max(min, Math.min(max, +e.target.value))); }}/></label>;
}

export function CaptionControls({ c, count, wordCount, style, bold, italic, both, fonts, preserve, scopeAll, onScope, onPreserve, patch, format, toggle, all, center, upload }: {
  c: Caption; count: number; wordCount: number; style: WordStyle; bold: boolean; italic: boolean; both: boolean; fonts: string[];
  preserve: boolean; scopeAll: boolean; onScope: (all: boolean) => void; onPreserve: (preserve: boolean) => void;
  patch: (patch: Partial<Caption>) => void; format: (patch: Partial<WordStyle>) => void; toggle: (kind: 'bold' | 'italic' | 'both') => void;
  all: (kind: 'typography' | 'position') => void; center: () => void; upload: () => void;
}) {
  return <><section className="property-group bulk-scope"><label>Edit scope<select aria-label="Edit scope" value={scopeAll ? 'all' : 'selected'} onChange={e => onScope(e.target.value === 'all')}><option value="selected">{wordCount ? `${wordCount} selected words` : `${count} selected caption${count === 1 ? '' : 's'}`}</option><option value="all">All captions</option></select></label><label className="check-row"><input type="checkbox" checked={preserve} onChange={e => onPreserve(e.target.checked)}/> Preserve word styling</label><p className="panel-help">Size changes keep relative emphasis. Base color changes keep custom word colors.</p></section>
    <section className="property-group"><label>Typography</label><select aria-label="Font family" value={c.font} onChange={e => patch({ font: e.target.value })}>{fonts.map(f => <option key={f} value={f}>{f.replace(' Variable', '')}</option>)}</select><div className="field-row"><select aria-label="Font style" value={both ? 'bold italic' : bold ? 'bold' : italic ? 'italic' : 'regular'} onChange={e => format({ bold: e.target.value.includes('bold'), italic: e.target.value.includes('italic') })}><option value="regular">Regular</option><option value="bold">Bold</option><option value="italic">Italic</option><option value="bold italic">Bold Italic</option></select><Field label="Size" value={style.size} min={8} max={400} onChange={size => format({ size })}/></div>
      <div className="format-buttons">{(['bold','italic','both'] as const).map((key, i) => <button key={key} aria-label={['Bold','Italic','Bold italic'][i]} aria-pressed={[bold, italic, both][i]} className={[bold, italic, both][i] ? 'active' : ''} onMouseDown={e => e.preventDefault()} onClick={() => toggle(key)} style={{ fontWeight: key !== 'italic' ? 700 : 400, fontStyle: key !== 'bold' ? 'italic' : 'normal' }}>{['B','I','BI'][i]}</button>)}<span className="separator"/>{(['left','center','right'] as const).map((align,i) => <button key={align} aria-label={`Align ${align}`} aria-pressed={c.align === align} className={c.align === align ? 'active' : ''} onClick={() => patch({ align })}>{i === 0 ? <AlignLeft size={15}/> : i === 1 ? <AlignCenter size={15}/> : <AlignRight size={15}/>}</button>)}</div>
      <label>Text color</label><div className="color-field"><input aria-label="Text color" type="color" value={style.color} onChange={e => format({ color: e.target.value })}/><span>{style.color.slice(1).toUpperCase()}</span></div><button className="text-button" onClick={upload}>Upload custom font</button><button className="quiet full" onClick={() => all('typography')}>Apply typography to all</button>
    </section>
    <section className="property-group"><label>Position & spacing</label><div className="field-row"><Field label="X %" value={c.x} min={0} max={100} step={.1} onChange={x => patch({ x })}/><Field label="Y %" value={c.y} min={0} max={100} step={.1} onChange={y => patch({ y })}/></div><div className="field-row"><Field label="Line" value={c.lineHeight} min={.7} max={3} step={.1} onChange={lineHeight => patch({ lineHeight })}/><Field label="Track" value={c.spacing} min={-10} max={30} step={.1} onChange={spacing => patch({ spacing })}/></div><label>Caption lines<select aria-label="Caption lines" value={c.lineMode ?? 'multi'} onChange={e => patch({ lineMode: e.target.value as 'single' | 'multi' })}><option value="single">Single line</option><option value="multi">Multi-line</option></select></label>{c.lineMode !== 'single' && <Field label="Wrap width %" value={c.width} min={5} max={100} onChange={width => patch({ width })}/>}<button className="quiet full" onClick={center}>Center on canvas</button><button className="quiet full" onClick={() => all('position')}>Apply position to all</button><p className="panel-help">Drag a corner to scale the text proportionally.</p></section>
  </>;
}

export function BreakControls({ rules, onChange, onApply, selected }: { rules: CaptionRules; onChange: (patch: Partial<CaptionRules>) => void; onApply: (all: boolean) => void; selected: boolean }) {
  return <details className="property-group control-details"><summary>Caption break rules</summary><label>Line mode<select aria-label="Generation line mode" value={rules.mode} onChange={e => onChange({ mode: e.target.value as 'single' | 'multi' })}><option value="single">Single line</option><option value="multi">Multi-line</option></select></label><Field label="Max words / caption" value={rules.maxWords} min={1} max={50} onChange={maxWords => onChange({ maxWords })}/><Field label="Max characters / caption" value={rules.maxChars} min={8} max={250} onChange={maxChars => onChange({ maxChars })}/><Field label="Max lines / caption" value={rules.mode === 'single' ? 1 : rules.maxLines} min={1} max={6} onChange={maxLines => onChange({ maxLines, mode: maxLines === 1 ? 'single' : 'multi' })}/><Field label="Break on pause (s)" value={rules.pause} min={.1} max={3} step={.1} onChange={pause => onChange({ pause })}/><p className="panel-help">Used for generated captions. Prefer punctuation and pauses; keep unbroken words intact. Reflow preserves word styles and timings.</p><button className="quiet full" disabled={!selected} onClick={() => onApply(false)}>Reflow selected captions</button><button className="quiet full" onClick={() => onApply(true)}>Reflow all captions</button></details>;
}

export function EmphasisControls({ options, enabled, selectedOnly, selectionCount, busy, onOptions, onEnabled, onSelectedOnly, onGenerate, onRemove, onCancel }: { options: EmphasisOptions; enabled: boolean; selectedOnly: boolean; selectionCount: number; busy: string; onOptions: (patch: Partial<EmphasisOptions>) => void; onEnabled: (enabled: boolean) => void; onSelectedOnly: (only: boolean) => void; onGenerate: () => void; onRemove: () => void; onCancel: () => void }) {
  const unavailable = !!busy || selectedOnly && !selectionCount;
  return <details className="property-group control-details"><summary>Auto Emphasis</summary><label className="check-row"><input type="checkbox" checked={enabled} disabled={!!busy} onChange={e => onEnabled(e.target.checked)}/> Auto Emphasis {enabled ? 'On' : 'Off'}</label><label>Intensity<select aria-label="Emphasis intensity" value={options.level} onChange={e => onOptions({ level: e.target.value as EmphasisOptions['level'] })}><option value="low">Low · a few key moments</option><option value="medium">Medium</option><option value="high">High</option></select></label><div className="emphasis-options">{(['bold','italic','boldItalic','size'] as const).map((key,i) => <label className="check-row" key={key}><input type="checkbox" checked={options[key]} onChange={e => onOptions({ [key]: e.target.checked })}/>{['Bold','Italic','Bold Italic','Larger text'][i]}</label>)}</div><label className="check-row"><input type="checkbox" checked={selectedOnly} onChange={e => onSelectedOnly(e.target.checked)}/> Selected captions only</label><p className="panel-help">Local AI finds meaningful words; pauses, emotion and isolated vocal energy refine the emphasis. Meaning analysis works best in English. Everything stays editable.</p>{busy ? <div className="local-progress"><span>{busy}</span><button className="quiet" onClick={onCancel}>Cancel</button></div> : <button className="quiet full" disabled={unavailable || !options.bold && !options.italic && !options.boldItalic && !options.size} onClick={onGenerate}>{enabled ? 'Regenerate emphasis' : 'Generate emphasis'}</button>}<button className="text-button" disabled={!!busy} onClick={onRemove}>Remove all auto emphasis</button></details>;
}
