import type { CaptionRules } from '@/lib/editor';
import type { EmphasisOptions } from '@/lib/caption-tools';
import { Field } from './caption-controls';

export type CaptionSetup = { rules: CaptionRules; emphasis: boolean; level: EmphasisOptions['level'] };
export default function CaptionSetupControls({ value, onChange, disabled }: { disabled?: boolean; value: CaptionSetup; onChange: (v: CaptionSetup) => void }) {
  const rules = value.rules, patch = (p: Partial<CaptionRules>) => onChange({ ...value, rules: { ...rules, ...p } });
  return <fieldset className="caption-setup" disabled={disabled}><legend>Caption setup</legend><label>Limit each caption by<select aria-label="Caption limit type" value={rules.limitBy ?? 'words'} onChange={e => patch({ limitBy: e.target.value as 'words' | 'characters' })}><option value="words">Maximum words</option><option value="characters">Maximum characters</option></select></label>{rules.limitBy === 'characters' ? <Field label="Maximum characters" value={rules.maxChars} min={8} max={250} onChange={maxChars => patch({ maxChars: Math.round(maxChars) })}/> : <Field label="Maximum words" value={rules.maxWords} min={1} max={50} onChange={maxWords => patch({ maxWords: Math.round(maxWords) })}/>}<label>Caption layout<select aria-label="Transcription caption layout" value={rules.mode} onChange={e => patch({ mode: e.target.value as 'single' | 'multi' })}><option value="single">Single line</option><option value="multi">Multi-line</option></select></label>{rules.mode === 'multi' && <Field label="Maximum lines" value={rules.maxLines} min={2} max={6} onChange={maxLines => patch({ maxLines: Math.round(maxLines) })}/>}<label className="check-row"><input type="checkbox" checked={value.emphasis} onChange={e => onChange({ ...value, emphasis: e.target.checked })}/> Auto Emphasis {value.emphasis ? 'On' : 'Off'}</label><label>Emphasis level<select aria-label="Transcription emphasis level" value={value.level} disabled={!value.emphasis} onChange={e => onChange({ ...value, level: e.target.value as CaptionSetup['level'] })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><p className="panel-help">Prefer punctuation and pauses. Keep whole words intact. Emphasis remains editable after generation.</p></fieldset>;
}
